// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogService menyediakan akses ke dialog native OS via Wails.
 * Di-bind ke frontend sebagai RPC.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * PickDirectory membuka dialog pemilihan direktori native OS.
 * Mengembalikan path yang dipilih, atau string kosong bila dibatalkan.
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2488026856);
}
