// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1895578398, id);
}

export function IsRunning(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1746492641, id);
}

/**
 * ListAvailableShells mengembalikan daftar shell/multiplexer yang ditemukan di PATH.
 */
export function ListAvailableShells(): $CancellablePromise<string[]> {
    return $Call.ByID(3529567282).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListRunning(): $CancellablePromise<string[]> {
    return $Call.ByID(4261720809).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LoadScrollback mengembalikan snapshot scrollback terakhir, atau "" bila tidak
 * ada.
 */
export function LoadScrollback(id: string): $CancellablePromise<string> {
    return $Call.ByID(3186707272, id);
}

export function ResizeSession(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3861567718, id, cols, rows);
}

/**
 * SaveScrollback menyimpan snapshot scrollback sebuah session. Best-effort:
 * kegagalan I/O atau truncate tidak menggagalkan operasi utama.
 */
export function SaveScrollback(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3820704785, id, data);
}

export function StartSession(opts: $models.StartOptions): $CancellablePromise<void> {
    return $Call.ByID(1851803826, opts);
}

export function WriteSession(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3217622507, id, data);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
