// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService mengelola siklus hidup PTY untuk setiap sesi terminal.
 * 
 * Setiap sesi yang berjalan = 1 PTY + 1 goroutine pembaca yang meng-emit
 * output ke frontend lewat domain.EventEmitter (PRD §8.2). Service ini di-bind
 * ke frontend sehingga metode ber-nama-eksport bisa dipanggil via RPC.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseSession mematikan PTY sebuah sesi (kill proses).
 */
export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1895578398, id);
}

/**
 * IsRunning melaporkan apakah sebuah sesi sedang aktif.
 */
export function IsRunning(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1746492641, id);
}

/**
 * ListRunning mengembalikan daftar id sesi yang sedang aktif.
 */
export function ListRunning(): $CancellablePromise<string[]> {
    return $Call.ByID(4261720809).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ResizeSession menyesuaikan ukuran PTY mengikuti ukuran pane di frontend.
 */
export function ResizeSession(id: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3861567718, id, cols, rows);
}

/**
 * StartSession membangkitkan PTY baru untuk sebuah sesi. Idempoten: bila sesi
 * dengan id tsb sudah berjalan, langsung sukses tanpa spawn baru.
 */
export function StartSession(opts: $models.StartOptions): $CancellablePromise<void> {
    return $Call.ByID(1851803826, opts);
}

/**
 * WriteSession menulis input (keystroke/paste) ke stdin shell.
 */
export function WriteSession(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3217622507, id, data);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
