// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CloseSession(id) {
    return $Call.ByID(1895578398, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRunning(id) {
    return $Call.ByID(1746492641, id);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListRunning() {
    return $Call.ByID(4261720809).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ResizeSession(id, cols, rows) {
    return $Call.ByID(3861567718, id, cols, rows);
}

/**
 * @param {$models.StartOptions} opts
 * @returns {$CancellablePromise<void>}
 */
export function StartSession(opts) {
    return $Call.ByID(1851803826, opts);
}

/**
 * @param {string} id
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function WriteSession(id, data) {
    return $Call.ByID(3217622507, id, data);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
