// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(1045489760).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DownloadAndApply(downloadURL: string): $CancellablePromise<void> {
    return $Call.ByID(2954134432, downloadURL);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
