// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * @param {string} workspaceID
 * @param {string} name
 * @param {string} shell
 * @param {string} cwd
 * @returns {$CancellablePromise<domain$0.SessionDef | null>}
 */
export function AddSession(workspaceID, name, shell, cwd) {
    return $Call.ByID(1986591254, workspaceID, name, shell, cwd).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} name
 * @param {string} color
 * @param {string} defaultCwd
 * @returns {$CancellablePromise<domain$0.Workspace | null>}
 */
export function CreateWorkspace(name, color, defaultCwd) {
    return $Call.ByID(1310262292, name, color, defaultCwd).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSession(workspaceID, sessionID) {
    return $Call.ByID(2078159696, workspaceID, sessionID);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorkspace(id) {
    return $Call.ByID(2727754625, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<domain$0.Workspace | null>}
 */
export function DuplicateWorkspace(id) {
    return $Call.ByID(913613637, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<(domain$0.Workspace | null)[]>}
 */
export function ListWorkspaces() {
    return $Call.ByID(2496591365).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function ReorderWorkspaces(ids) {
    return $Call.ByID(2064324940, ids);
}

/**
 * @param {domain$0.SessionDef | null} updated
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSession(updated) {
    return $Call.ByID(4083162826, updated);
}

/**
 * @param {domain$0.Workspace | null} updated
 * @returns {$CancellablePromise<void>}
 */
export function UpdateWorkspace(updated) {
    return $Call.ByID(3766130551, updated);
}

// Private type creation functions
const $$createType0 = domain$0.SessionDef.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = domain$0.Workspace.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
