// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService mengelola CRUD workspace & definisi sesi serta
 * persistensinya. Di-bind ke frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * AddSession menambahkan definisi sesi baru ke sebuah workspace.
 */
export function AddSession(workspaceID: string, name: string, shell: string, cwd: string, startupCommand: string): $CancellablePromise<domain$0.SessionDef | null> {
    return $Call.ByID(1986591254, workspaceID, name, shell, cwd, startupCommand).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateWorkspace membuat workspace baru dan mengembalikannya.
 */
export function CreateWorkspace(name: string, color: string, defaultCwd: string): $CancellablePromise<domain$0.Workspace | null> {
    return $Call.ByID(1310262292, name, color, defaultCwd).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DeleteSession menghapus definisi sesi dari workspace.
 */
export function DeleteSession(workspaceID: string, sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2078159696, workspaceID, sessionID);
}

/**
 * DeleteWorkspace menghapus workspace beserta definisi sesinya.
 */
export function DeleteWorkspace(id: string): $CancellablePromise<void> {
    return $Call.ByID(2727754625, id);
}

/**
 * DuplicateWorkspace menyalin workspace beserta definisi sesinya (FR-5).
 * Id baru di-generate untuk workspace dan tiap sesi; tidak ada PTY yang dibuat.
 */
export function DuplicateWorkspace(id: string): $CancellablePromise<domain$0.Workspace | null> {
    return $Call.ByID(913613637, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListWorkspaces mengembalikan seluruh workspace yang tersimpan.
 */
export function ListWorkspaces(): $CancellablePromise<(domain$0.Workspace | null)[]> {
    return $Call.ByID(2496591365).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * UpdateSession menyimpan perubahan definisi sesi (rename, env, autoStart, dll).
 */
export function UpdateSession(updated: domain$0.SessionDef | null): $CancellablePromise<void> {
    return $Call.ByID(4083162826, updated);
}

/**
 * UpdateWorkspace menyimpan perubahan metadata workspace (nama, warna, cwd, env).
 */
export function UpdateWorkspace(updated: domain$0.Workspace | null): $CancellablePromise<void> {
    return $Call.ByID(3766130551, updated);
}

// Private type creation functions
const $$createType0 = domain$0.SessionDef.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = domain$0.Workspace.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
