// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * SessionDef adalah definisi sebuah sesi terminal yang dipersist.
 * Status runtime (running/exited, PID) TIDAK disimpan di sini — itu dikelola
 * oleh SessionService secara in-memory (PRD §5.2).
 */
export class SessionDef {
    "id": string;
    "workspaceId": string;
    "name": string;
    "shell": string;
    "cwd": string;
    "env": { [_ in string]?: string };
    "autoStart": boolean;
    "layout"?: { [_ in string]?: any };

    /** Creates a new SessionDef instance. */
    constructor($$source: Partial<SessionDef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("shell" in $$source)) {
            this["shell"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionDef instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionDef {
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField5_0($$parsedSource["env"]);
        }
        if ("layout" in $$parsedSource) {
            $$parsedSource["layout"] = $$createField7_0($$parsedSource["layout"]);
        }
        return new SessionDef($$parsedSource as Partial<SessionDef>);
    }
}

/**
 * Workspace adalah kumpulan sesi terminal yang dikelompokkan per-proyek.
 * Struktur ini dipersist ke file konfig (lihat lapisan infra/config).
 */
export class Workspace {
    "id": string;
    "name": string;
    "color": string;
    "defaultCwd": string;
    "startupCommand": string;
    "env": { [_ in string]?: string };
    "sessions": (SessionDef | null)[];
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Workspace instance. */
    constructor($$source: Partial<Workspace> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("defaultCwd" in $$source)) {
            this["defaultCwd"] = "";
        }
        if (!("startupCommand" in $$source)) {
            this["startupCommand"] = "";
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Workspace instance from a string or object.
     */
    static createFrom($$source: any = {}): Workspace {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField5_0($$parsedSource["env"]);
        }
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField6_0($$parsedSource["sessions"]);
        }
        return new Workspace($$parsedSource as Partial<Workspace>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = SessionDef.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
